sonar.projectKey=remmody_VaultixIMQ
sonar.organization=r3-code

# Source and Test directories
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go,frontend/src/**/*.test.js

# Exclusions
sonar.exclusions=frontend/node_modules/**,frontend/dist/**,frontend/wailsjs/**,build/**,vendor/**,**/*.txt,**/*.md

# Go specific configuration
sonar.go.coverage.reportPaths=cover.out
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info