// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['AddAccount'](arg1, arg2, arg3, arg4, arg5);
}

export function AddTOTP(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddTOTP'](arg1, arg2, arg3);
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function CopyToClipboard(arg1) {
  return window['go']['app']['App']['CopyToClipboard'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['app']['App']['DeleteAccount'](arg1);
}

export function DeleteTOTP(arg1) {
  return window['go']['app']['App']['DeleteTOTP'](arg1);
}

export function ExportProfile(arg1, arg2) {
  return window['go']['app']['App']['ExportProfile'](arg1, arg2);
}

export function FetchBody(arg1, arg2) {
  return window['go']['app']['App']['FetchBody'](arg1, arg2);
}

export function FetchInbox(arg1, arg2) {
  return window['go']['app']['App']['FetchInbox'](arg1, arg2);
}

export function GenerateTOTP(arg1) {
  return window['go']['app']['App']['GenerateTOTP'](arg1);
}

export function GetAboutInfo() {
  return window['go']['app']['App']['GetAboutInfo']();
}

export function GetAccounts() {
  return window['go']['app']['App']['GetAccounts']();
}

export function GetCachedMessages(arg1) {
  return window['go']['app']['App']['GetCachedMessages'](arg1);
}

export function GetNextSync() {
  return window['go']['app']['App']['GetNextSync']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetTOTPList() {
  return window['go']['app']['App']['GetTOTPList']();
}

export function ImportProfile(arg1, arg2) {
  return window['go']['app']['App']['ImportProfile'](arg1, arg2);
}

export function IsLocked() {
  return window['go']['app']['App']['IsLocked']();
}

export function IsPasswordSet() {
  return window['go']['app']['App']['IsPasswordSet']();
}

export function LockApp() {
  return window['go']['app']['App']['LockApp']();
}

export function MarkAllAsRead(arg1) {
  return window['go']['app']['App']['MarkAllAsRead'](arg1);
}

export function MarkAsRead(arg1, arg2) {
  return window['go']['app']['App']['MarkAsRead'](arg1, arg2);
}

export function NeedsSetup() {
  return window['go']['app']['App']['NeedsSetup']();
}

export function SelectOpenPath() {
  return window['go']['app']['App']['SelectOpenPath']();
}

export function SelectSavePath() {
  return window['go']['app']['App']['SelectSavePath']();
}

export function SetAppPassword(arg1) {
  return window['go']['app']['App']['SetAppPassword'](arg1);
}

export function SkipAppPasswordSetup() {
  return window['go']['app']['App']['SkipAppPasswordSetup']();
}

export function UnlockApp(arg1) {
  return window['go']['app']['App']['UnlockApp'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}

export function VerifyAppPassword(arg1) {
  return window['go']['app']['App']['VerifyAppPassword'](arg1);
}
