// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {mail} from '../models';
import {totp} from '../models';

export function AddAccount(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<boolean>;

export function AddTOTP(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CheckForUpdates():Promise<app.UpdateInfo>;

export function CopyToClipboard(arg1:string):Promise<boolean>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteTOTP(arg1:string):Promise<void>;

export function ExportProfile(arg1:string,arg2:string):Promise<void>;

export function FetchBody(arg1:string,arg2:number):Promise<Array<unknown>>;

export function FetchInbox(arg1:string,arg2:number):Promise<Array<mail.Message>>;

export function GenerateTOTP(arg1:string):Promise<totp.Response>;

export function GetAboutInfo():Promise<app.AboutInfo>;

export function GetAccounts():Promise<Array<mail.Account>>;

export function GetCachedMessages(arg1:string):Promise<Array<mail.Message>>;

export function GetNextSync():Promise<number>;

export function GetSettings():Promise<app.Settings>;

export function GetTOTPList():Promise<Array<totp.Entry>>;

export function ImportProfile(arg1:string,arg2:string):Promise<void>;

export function IsLocked():Promise<boolean>;

export function IsPasswordSet():Promise<boolean>;

export function LockApp():Promise<void>;

export function MarkAllAsRead(arg1:string):Promise<void>;

export function MarkAsRead(arg1:string,arg2:number):Promise<void>;

export function NeedsSetup():Promise<boolean>;

export function SelectOpenPath():Promise<string>;

export function SelectSavePath():Promise<string>;

export function SetAppPassword(arg1:string):Promise<void>;

export function SkipAppPasswordSetup():Promise<void>;

export function UnlockApp(arg1:string):Promise<boolean>;

export function UpdateSettings(arg1:app.Settings):Promise<void>;

export function VerifyAppPassword(arg1:string):Promise<boolean>;
